use utoipa::OpenApi;

use super::handlers::{
    AlertmanagerAlert, AlertmanagerAlertResult, AlertmanagerWebhookPayload,
    AlertmanagerWebhookResponse, AuditListResponse, BatchEventRequest, BatchEventResponse,
    BatchEventResult, BulkAcknowledgeRequest, BulkAcknowledgeResponse, BulkAcknowledgeResult,
    BulkWithdrawRequest, BulkWithdrawResponse, BulkWithdrawResult, CorrelationContext,
    ErrorResponse, EventResponse, EventsListResponse, FastNetMonAttackDetails, FastNetMonPayload,
    HealthResponse, IpHistoryResponse, MitigationResponse, MitigationsListResponse,
    PublicHealthResponse, ReloadResponse, SignalGroupDetailResponse, SignalGroupsListResponse,
    TimeseriesResponse, WebhookEventResult, WebhookResponse,
};
use crate::correlation::config::{CorrelationConfig, SourceConfig};
use crate::correlation::engine::{
    CorrelationExplanation, SignalGroup, SignalGroupEvent, SignalGroupStatus, SourceContribution,
};
use crate::correlation::webhook::{WebhookAdapter, WebhookAuth, WebhookFieldMap};
use crate::db::{GlobalStats, NotificationPreferences, PopInfo, PopStats, SafelistEntry};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "prefixd API",
        version = "1.0.0",
        description = "BGP FlowSpec routing policy daemon for automated DDoS mitigation",
        license(name = "MIT"),
        contact(name = "prefixd")
    ),
    servers(
        (url = "/", description = "Local server")
    ),
    paths(
        super::handlers::health,
        super::handlers::health_detail,
        super::handlers::ingest_event,
        super::handlers::ingest_events_batch,
        super::handlers::list_mitigations,
        super::handlers::get_mitigation,
        super::handlers::bulk_withdraw_mitigations,
        super::handlers::bulk_acknowledge_mitigations,
        super::handlers::list_events,
        super::handlers::list_audit,
        super::handlers::get_stats,
        super::handlers::list_pops,
        super::handlers::get_config_settings,
        super::handlers::get_config_inventory,
        super::handlers::get_config_playbooks,
        super::handlers::update_playbooks,
        super::handlers::get_alerting_config,
        super::handlers::update_alerting_config,
        super::handlers::test_alerting,
        super::handlers::get_timeseries,
        super::handlers::get_ip_history,
        super::handlers::get_notification_preferences,
        super::handlers::update_notification_preferences,
        super::handlers::generate_incident_report,
        super::handlers::list_signal_groups,
        super::handlers::get_signal_group,
        super::handlers::ingest_alertmanager,
        super::handlers::ingest_fastnetmon,
        super::handlers::ingest_webhook,
        super::handlers::ingest_corroborator,
        super::handlers::get_correlation_config,
        super::handlers::update_correlation_config,
    ),
    components(
        schemas(
            EventResponse,
            MitigationResponse,
            MitigationsListResponse,
            PublicHealthResponse,
            HealthResponse,
            ErrorResponse,
            ReloadResponse,
            GlobalStats,
            PopStats,
            PopInfo,
            SafelistEntry,
            TimeseriesResponse,
            IpHistoryResponse,
            BulkWithdrawRequest,
            BulkWithdrawResponse,
            BulkWithdrawResult,
            BulkAcknowledgeRequest,
            BulkAcknowledgeResponse,
            BulkAcknowledgeResult,
            BatchEventRequest,
            BatchEventResponse,
            BatchEventResult,
            EventsListResponse,
            AuditListResponse,
            crate::db::TimeseriesBucket,
            NotificationPreferences,
            CorrelationContext,
            SignalGroupsListResponse,
            SignalGroupDetailResponse,
            AlertmanagerWebhookPayload,
            AlertmanagerAlert,
            AlertmanagerWebhookResponse,
            AlertmanagerAlertResult,
            FastNetMonPayload,
            FastNetMonAttackDetails,
            SignalGroup,
            SignalGroupEvent,
            SignalGroupStatus,
            CorrelationExplanation,
            SourceContribution,
            CorrelationConfig,
            SourceConfig,
            WebhookAdapter,
            WebhookAuth,
            WebhookFieldMap,
            WebhookResponse,
            WebhookEventResult,
            super::handlers::CorroboratorInput,
            super::handlers::CorroboratorResponse,
            crate::correlation::PrimaryDimensions,
            crate::correlation::MatchDimension,
            crate::correlation::SourceMode,
        )
    ),
    tags(
        (name = "health", description = "Health and status endpoints"),
        (name = "events", description = "Attack event ingestion"),
        (name = "mitigations", description = "Mitigation management"),
        (name = "safelist", description = "Safelist management"),
        (name = "config", description = "Configuration management"),
        (name = "multi-pop", description = "Multi-POP coordination"),
        (name = "stats", description = "Statistics and timeseries"),
        (name = "ip-history", description = "IP history and context"),
        (name = "preferences", description = "Notification preferences"),
        (name = "reports", description = "Incident reports"),
        (name = "signal-groups", description = "Signal group correlation management"),
        (name = "signals", description = "Signal adapter webhook endpoints"),
    )
)]
pub struct ApiDoc;
